-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hs2axis is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_r_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    out_r_TVALID : OUT STD_LOGIC;
    out_r_TREADY : IN STD_LOGIC;
    out_r_TLAST : OUT STD_LOGIC;
    ch_div_K_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ch_div_K_empty_n : IN STD_LOGIC;
    ch_div_K_read : OUT STD_LOGIC;
    height_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    height_out_empty_n : IN STD_LOGIC;
    height_out_read : OUT STD_LOGIC;
    width_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    width_out_empty_n : IN STD_LOGIC;
    width_out_read : OUT STD_LOGIC;
    stream_tp2_V_V_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    stream_tp2_V_V_empty_n : IN STD_LOGIC;
    stream_tp2_V_V_read : OUT STD_LOGIC );
end;


architecture behav of hs2axis is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal out_V_data_V_1_data_out : STD_LOGIC_VECTOR (127 downto 0);
    signal out_V_data_V_1_vld_in : STD_LOGIC;
    signal out_V_data_V_1_vld_out : STD_LOGIC;
    signal out_V_data_V_1_ack_in : STD_LOGIC;
    signal out_V_data_V_1_ack_out : STD_LOGIC;
    signal out_V_data_V_1_payload_A : STD_LOGIC_VECTOR (127 downto 0);
    signal out_V_data_V_1_payload_B : STD_LOGIC_VECTOR (127 downto 0);
    signal out_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal out_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal out_V_data_V_1_sel : STD_LOGIC;
    signal out_V_data_V_1_load_A : STD_LOGIC;
    signal out_V_data_V_1_load_B : STD_LOGIC;
    signal out_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal out_V_last_1_data_out : STD_LOGIC;
    signal out_V_last_1_vld_in : STD_LOGIC;
    signal out_V_last_1_vld_out : STD_LOGIC;
    signal out_V_last_1_ack_in : STD_LOGIC;
    signal out_V_last_1_ack_out : STD_LOGIC;
    signal out_V_last_1_payload_A : STD_LOGIC;
    signal out_V_last_1_payload_B : STD_LOGIC;
    signal out_V_last_1_sel_rd : STD_LOGIC := '0';
    signal out_V_last_1_sel_wr : STD_LOGIC := '0';
    signal out_V_last_1_sel : STD_LOGIC;
    signal out_V_last_1_load_A : STD_LOGIC;
    signal out_V_last_1_load_B : STD_LOGIC;
    signal out_V_last_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_V_last_1_state_cmp_full : STD_LOGIC;
    signal out_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln48_reg_208 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln48_reg_208_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ch_div_K_blk_n : STD_LOGIC;
    signal height_out_blk_n : STD_LOGIC;
    signal width_out_blk_n : STD_LOGIC;
    signal stream_tp2_V_V_blk_n : STD_LOGIC;
    signal i_0_i_i_reg_133 : STD_LOGIC_VECTOR (30 downto 0);
    signal ch_div_K_read_reg_177 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal height_out_read_reg_182 : STD_LOGIC_VECTOR (31 downto 0);
    signal width_out_read_reg_187 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln48_fu_144_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln48_reg_192 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mul_ln48_1_fu_148_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln48_1_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln55_fu_152_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln55_reg_203 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln48_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_166_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_last_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_217 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state5 : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln48_fu_157_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_block_state8 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((out_V_last_1_state = ap_const_lv2_1) or (out_V_data_V_1_state = ap_const_lv2_1) or ((out_V_data_V_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)) or ((out_V_last_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state5)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state5);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    out_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                out_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_V_data_V_1_ack_out = ap_const_logic_1) and (out_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        out_V_data_V_1_sel_rd <= not(out_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                out_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((out_V_data_V_1_ack_in = ap_const_logic_1) and (out_V_data_V_1_vld_in = ap_const_logic_1))) then 
                                        out_V_data_V_1_sel_wr <= not(out_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    out_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                out_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_V_data_V_1_state = ap_const_lv2_2) and (out_V_data_V_1_vld_in = ap_const_logic_0)) or ((out_V_data_V_1_state = ap_const_lv2_3) and (out_V_data_V_1_vld_in = ap_const_logic_0) and (out_V_data_V_1_ack_out = ap_const_logic_1)))) then 
                    out_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((out_V_data_V_1_state = ap_const_lv2_1) and (out_r_TREADY = ap_const_logic_0)) or ((out_V_data_V_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0) and (out_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    out_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_V_data_V_1_vld_in = ap_const_logic_0) and (out_V_data_V_1_ack_out = ap_const_logic_1))) and not(((out_r_TREADY = ap_const_logic_0) and (out_V_data_V_1_vld_in = ap_const_logic_1))) and (out_V_data_V_1_state = ap_const_lv2_3)) or ((out_V_data_V_1_state = ap_const_lv2_1) and (out_V_data_V_1_ack_out = ap_const_logic_1)) or ((out_V_data_V_1_state = ap_const_lv2_2) and (out_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    out_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    out_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_V_last_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                out_V_last_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_V_last_1_ack_out = ap_const_logic_1) and (out_V_last_1_vld_out = ap_const_logic_1))) then 
                                        out_V_last_1_sel_rd <= not(out_V_last_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_V_last_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                out_V_last_1_sel_wr <= ap_const_logic_0;
            else
                if (((out_V_last_1_vld_in = ap_const_logic_1) and (out_V_last_1_ack_in = ap_const_logic_1))) then 
                                        out_V_last_1_sel_wr <= not(out_V_last_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    out_V_last_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                out_V_last_1_state <= ap_const_lv2_0;
            else
                if ((((out_V_last_1_state = ap_const_lv2_2) and (out_V_last_1_vld_in = ap_const_logic_0)) or ((out_V_last_1_state = ap_const_lv2_3) and (out_V_last_1_vld_in = ap_const_logic_0) and (out_V_last_1_ack_out = ap_const_logic_1)))) then 
                    out_V_last_1_state <= ap_const_lv2_2;
                elsif ((((out_V_last_1_state = ap_const_lv2_1) and (out_r_TREADY = ap_const_logic_0)) or ((out_V_last_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0) and (out_V_last_1_vld_in = ap_const_logic_1)))) then 
                    out_V_last_1_state <= ap_const_lv2_1;
                elsif (((not(((out_V_last_1_vld_in = ap_const_logic_0) and (out_V_last_1_ack_out = ap_const_logic_1))) and not(((out_r_TREADY = ap_const_logic_0) and (out_V_last_1_vld_in = ap_const_logic_1))) and (out_V_last_1_state = ap_const_lv2_3)) or ((out_V_last_1_state = ap_const_lv2_1) and (out_V_last_1_ack_out = ap_const_logic_1)) or ((out_V_last_1_state = ap_const_lv2_2) and (out_V_last_1_vld_in = ap_const_logic_1)))) then 
                    out_V_last_1_state <= ap_const_lv2_3;
                else 
                    out_V_last_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    i_0_i_i_reg_133_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln48_fu_161_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_0_i_i_reg_133 <= i_fu_166_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                i_0_i_i_reg_133 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln55_reg_203 <= add_ln55_fu_152_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((width_out_empty_n = ap_const_logic_0) or (height_out_empty_n = ap_const_logic_0) or (ch_div_K_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                ch_div_K_read_reg_177 <= ch_div_K_dout;
                height_out_read_reg_182 <= height_out_dout;
                width_out_read_reg_187 <= width_out_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln48_reg_208 <= icmp_ln48_fu_161_p2;
                icmp_ln48_reg_208_pp0_iter1_reg <= icmp_ln48_reg_208;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_ln48_1_reg_197 <= mul_ln48_1_fu_148_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                mul_ln48_reg_192 <= mul_ln48_fu_144_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_V_data_V_1_load_A = ap_const_logic_1)) then
                out_V_data_V_1_payload_A <= stream_tp2_V_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_V_data_V_1_load_B = ap_const_logic_1)) then
                out_V_data_V_1_payload_B <= stream_tp2_V_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_V_last_1_load_A = ap_const_logic_1)) then
                out_V_last_1_payload_A <= tmp_last_reg_217(0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_V_last_1_load_B = ap_const_logic_1)) then
                out_V_last_1_payload_B <= tmp_last_reg_217(0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln48_fu_161_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_last_reg_217 <= tmp_last_fu_172_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, out_r_TREADY, out_V_data_V_1_state, out_V_last_1_state, ch_div_K_empty_n, height_out_empty_n, width_out_empty_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln48_fu_161_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((width_out_empty_n = ap_const_logic_0) or (height_out_empty_n = ap_const_logic_0) or (ch_div_K_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln48_fu_161_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((icmp_ln48_fu_161_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                if ((not(((out_V_last_1_state = ap_const_lv2_1) or (out_V_data_V_1_state = ap_const_lv2_1) or ((out_V_data_V_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)) or ((out_V_last_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln55_fu_152_p2 <= std_logic_vector(unsigned(mul_ln48_1_reg_197) + unsigned(ap_const_lv32_FFFFFFFF));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state8 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(stream_tp2_V_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln48_reg_208)
    begin
                ap_block_pp0_stage0_01001 <= ((icmp_ln48_reg_208 = ap_const_lv1_1) and (stream_tp2_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(stream_tp2_V_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln48_reg_208, ap_enable_reg_pp0_iter2, ap_block_state6_io, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state7_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln48_reg_208 = ap_const_lv1_1) and (stream_tp2_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(stream_tp2_V_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln48_reg_208, ap_enable_reg_pp0_iter2, ap_block_state6_io, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state7_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln48_reg_208 = ap_const_lv1_1) and (stream_tp2_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, ch_div_K_empty_n, height_out_empty_n, width_out_empty_n)
    begin
                ap_block_state1 <= ((width_out_empty_n = ap_const_logic_0) or (height_out_empty_n = ap_const_logic_0) or (ch_div_K_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state5_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_io_assign_proc : process(out_V_data_V_1_ack_in, icmp_ln48_reg_208)
    begin
                ap_block_state6_io <= ((icmp_ln48_reg_208 = ap_const_lv1_1) and (out_V_data_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_block_state6_pp0_stage0_iter1_assign_proc : process(stream_tp2_V_V_empty_n, icmp_ln48_reg_208)
    begin
                ap_block_state6_pp0_stage0_iter1 <= ((icmp_ln48_reg_208 = ap_const_lv1_1) and (stream_tp2_V_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state7_io_assign_proc : process(out_V_data_V_1_ack_in, icmp_ln48_reg_208_pp0_iter1_reg)
    begin
                ap_block_state7_io <= ((icmp_ln48_reg_208_pp0_iter1_reg = ap_const_lv1_1) and (out_V_data_V_1_ack_in = ap_const_logic_0));
    end process;

        ap_block_state7_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_assign_proc : process(out_r_TREADY, out_V_data_V_1_state, out_V_last_1_state)
    begin
                ap_block_state8 <= ((out_V_last_1_state = ap_const_lv2_1) or (out_V_data_V_1_state = ap_const_lv2_1) or ((out_V_data_V_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)) or ((out_V_last_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state5_assign_proc : process(icmp_ln48_fu_161_p2)
    begin
        if ((icmp_ln48_fu_161_p2 = ap_const_lv1_0)) then 
            ap_condition_pp0_exit_iter0_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, out_r_TREADY, out_V_data_V_1_state, out_V_last_1_state, ap_CS_fsm_state8)
    begin
        if ((not(((out_V_last_1_state = ap_const_lv2_1) or (out_V_data_V_1_state = ap_const_lv2_1) or ((out_V_data_V_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)) or ((out_V_last_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(out_r_TREADY, out_V_data_V_1_state, out_V_last_1_state, ap_CS_fsm_state8)
    begin
        if ((not(((out_V_last_1_state = ap_const_lv2_1) or (out_V_data_V_1_state = ap_const_lv2_1) or ((out_V_data_V_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)) or ((out_V_last_1_state = ap_const_lv2_3) and (out_r_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ch_div_K_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ch_div_K_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ch_div_K_blk_n <= ch_div_K_empty_n;
        else 
            ch_div_K_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ch_div_K_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ch_div_K_empty_n, height_out_empty_n, width_out_empty_n)
    begin
        if ((not(((width_out_empty_n = ap_const_logic_0) or (height_out_empty_n = ap_const_logic_0) or (ch_div_K_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ch_div_K_read <= ap_const_logic_1;
        else 
            ch_div_K_read <= ap_const_logic_0;
        end if; 
    end process;


    height_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_out_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_out_blk_n <= height_out_empty_n;
        else 
            height_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    height_out_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ch_div_K_empty_n, height_out_empty_n, width_out_empty_n)
    begin
        if ((not(((width_out_empty_n = ap_const_logic_0) or (height_out_empty_n = ap_const_logic_0) or (ch_div_K_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_out_read <= ap_const_logic_1;
        else 
            height_out_read <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_166_p2 <= std_logic_vector(unsigned(i_0_i_i_reg_133) + unsigned(ap_const_lv31_1));
    icmp_ln48_fu_161_p2 <= "1" when (signed(zext_ln48_fu_157_p1) < signed(mul_ln48_1_reg_197)) else "0";
    mul_ln48_1_fu_148_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln48_reg_192) * signed(height_out_read_reg_182))), 32));
    mul_ln48_fu_144_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ch_div_K_read_reg_177) * signed(width_out_read_reg_187))), 32));
    out_V_data_V_1_ack_in <= out_V_data_V_1_state(1);
    out_V_data_V_1_ack_out <= out_r_TREADY;

    out_V_data_V_1_data_out_assign_proc : process(out_V_data_V_1_payload_A, out_V_data_V_1_payload_B, out_V_data_V_1_sel)
    begin
        if ((out_V_data_V_1_sel = ap_const_logic_1)) then 
            out_V_data_V_1_data_out <= out_V_data_V_1_payload_B;
        else 
            out_V_data_V_1_data_out <= out_V_data_V_1_payload_A;
        end if; 
    end process;

    out_V_data_V_1_load_A <= (out_V_data_V_1_state_cmp_full and not(out_V_data_V_1_sel_wr));
    out_V_data_V_1_load_B <= (out_V_data_V_1_state_cmp_full and out_V_data_V_1_sel_wr);
    out_V_data_V_1_sel <= out_V_data_V_1_sel_rd;
    out_V_data_V_1_state_cmp_full <= '0' when (out_V_data_V_1_state = ap_const_lv2_1) else '1';

    out_V_data_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln48_reg_208, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln48_reg_208 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            out_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_V_data_V_1_vld_out <= out_V_data_V_1_state(0);
    out_V_last_1_ack_in <= out_V_last_1_state(1);
    out_V_last_1_ack_out <= out_r_TREADY;

    out_V_last_1_data_out_assign_proc : process(out_V_last_1_payload_A, out_V_last_1_payload_B, out_V_last_1_sel)
    begin
        if ((out_V_last_1_sel = ap_const_logic_1)) then 
            out_V_last_1_data_out <= out_V_last_1_payload_B;
        else 
            out_V_last_1_data_out <= out_V_last_1_payload_A;
        end if; 
    end process;

    out_V_last_1_load_A <= (out_V_last_1_state_cmp_full and not(out_V_last_1_sel_wr));
    out_V_last_1_load_B <= (out_V_last_1_state_cmp_full and out_V_last_1_sel_wr);
    out_V_last_1_sel <= out_V_last_1_sel_rd;
    out_V_last_1_state_cmp_full <= '0' when (out_V_last_1_state = ap_const_lv2_1) else '1';

    out_V_last_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln48_reg_208, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln48_reg_208 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_V_last_1_vld_in <= ap_const_logic_1;
        else 
            out_V_last_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_V_last_1_vld_out <= out_V_last_1_state(0);
    out_r_TDATA <= out_V_data_V_1_data_out;

    out_r_TDATA_blk_n_assign_proc : process(out_V_data_V_1_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln48_reg_208, ap_enable_reg_pp0_iter2, icmp_ln48_reg_208_pp0_iter1_reg)
    begin
        if ((((icmp_ln48_reg_208_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((icmp_ln48_reg_208 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            out_r_TDATA_blk_n <= out_V_data_V_1_state(1);
        else 
            out_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_r_TLAST <= out_V_last_1_data_out;
    out_r_TVALID <= out_V_last_1_state(0);

    stream_tp2_V_V_blk_n_assign_proc : process(stream_tp2_V_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln48_reg_208)
    begin
        if (((icmp_ln48_reg_208 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            stream_tp2_V_V_blk_n <= stream_tp2_V_V_empty_n;
        else 
            stream_tp2_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_tp2_V_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln48_reg_208, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln48_reg_208 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_tp2_V_V_read <= ap_const_logic_1;
        else 
            stream_tp2_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_last_fu_172_p2 <= "1" when (zext_ln48_fu_157_p1 = add_ln55_reg_203) else "0";

    width_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_out_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_out_blk_n <= width_out_empty_n;
        else 
            width_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    width_out_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ch_div_K_empty_n, height_out_empty_n, width_out_empty_n)
    begin
        if ((not(((width_out_empty_n = ap_const_logic_0) or (height_out_empty_n = ap_const_logic_0) or (ch_div_K_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_out_read <= ap_const_logic_1;
        else 
            width_out_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln48_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_i_i_reg_133),32));
end behav;
