// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hs2axis.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hs2axis::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic hs2axis::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> hs2axis::ap_ST_fsm_state1 = "1";
const sc_lv<6> hs2axis::ap_ST_fsm_state2 = "10";
const sc_lv<6> hs2axis::ap_ST_fsm_state3 = "100";
const sc_lv<6> hs2axis::ap_ST_fsm_state4 = "1000";
const sc_lv<6> hs2axis::ap_ST_fsm_pp0_stage0 = "10000";
const sc_lv<6> hs2axis::ap_ST_fsm_state8 = "100000";
const sc_lv<32> hs2axis::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool hs2axis::ap_const_boolean_1 = true;
const sc_lv<1> hs2axis::ap_const_lv1_0 = "0";
const sc_lv<1> hs2axis::ap_const_lv1_1 = "1";
const sc_lv<2> hs2axis::ap_const_lv2_0 = "00";
const sc_lv<2> hs2axis::ap_const_lv2_2 = "10";
const sc_lv<2> hs2axis::ap_const_lv2_3 = "11";
const sc_lv<2> hs2axis::ap_const_lv2_1 = "1";
const sc_lv<32> hs2axis::ap_const_lv32_4 = "100";
const bool hs2axis::ap_const_boolean_0 = false;
const sc_lv<32> hs2axis::ap_const_lv32_1 = "1";
const sc_lv<32> hs2axis::ap_const_lv32_2 = "10";
const sc_lv<32> hs2axis::ap_const_lv32_3 = "11";
const sc_lv<31> hs2axis::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> hs2axis::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<31> hs2axis::ap_const_lv31_1 = "1";
const sc_lv<32> hs2axis::ap_const_lv32_5 = "101";

hs2axis::hs2axis(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln55_fu_152_p2);
    sensitive << ( mul_ln48_1_reg_197 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( stream_tp2_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln48_reg_208 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( stream_tp2_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln48_reg_208 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state6_io );
    sensitive << ( ap_block_state7_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( stream_tp2_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln48_reg_208 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state6_io );
    sensitive << ( ap_block_state7_io );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ch_div_K_empty_n );
    sensitive << ( height_out_empty_n );
    sensitive << ( width_out_empty_n );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state6_io);
    sensitive << ( out_V_data_V_1_ack_in );
    sensitive << ( icmp_ln48_reg_208 );

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);
    sensitive << ( stream_tp2_V_V_empty_n );
    sensitive << ( icmp_ln48_reg_208 );

    SC_METHOD(thread_ap_block_state7_io);
    sensitive << ( out_V_data_V_1_ack_in );
    sensitive << ( icmp_ln48_reg_208_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state8);
    sensitive << ( out_r_TREADY );
    sensitive << ( out_V_data_V_1_state );
    sensitive << ( out_V_last_1_state );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state5);
    sensitive << ( icmp_ln48_fu_161_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( out_r_TREADY );
    sensitive << ( out_V_data_V_1_state );
    sensitive << ( out_V_last_1_state );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( out_r_TREADY );
    sensitive << ( out_V_data_V_1_state );
    sensitive << ( out_V_last_1_state );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ch_div_K_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ch_div_K_empty_n );

    SC_METHOD(thread_ch_div_K_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ch_div_K_empty_n );
    sensitive << ( height_out_empty_n );
    sensitive << ( width_out_empty_n );

    SC_METHOD(thread_height_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( height_out_empty_n );

    SC_METHOD(thread_height_out_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ch_div_K_empty_n );
    sensitive << ( height_out_empty_n );
    sensitive << ( width_out_empty_n );

    SC_METHOD(thread_i_fu_166_p2);
    sensitive << ( i_0_i_i_reg_133 );

    SC_METHOD(thread_icmp_ln48_fu_161_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( mul_ln48_1_reg_197 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln48_fu_157_p1 );

    SC_METHOD(thread_mul_ln48_1_fu_148_p2);
    sensitive << ( height_out_read_reg_182 );
    sensitive << ( mul_ln48_reg_192 );

    SC_METHOD(thread_mul_ln48_fu_144_p2);
    sensitive << ( ch_div_K_read_reg_177 );
    sensitive << ( width_out_read_reg_187 );

    SC_METHOD(thread_out_V_data_V_1_ack_in);
    sensitive << ( out_V_data_V_1_state );

    SC_METHOD(thread_out_V_data_V_1_ack_out);
    sensitive << ( out_r_TREADY );

    SC_METHOD(thread_out_V_data_V_1_data_out);
    sensitive << ( out_V_data_V_1_payload_A );
    sensitive << ( out_V_data_V_1_payload_B );
    sensitive << ( out_V_data_V_1_sel );

    SC_METHOD(thread_out_V_data_V_1_load_A);
    sensitive << ( out_V_data_V_1_sel_wr );
    sensitive << ( out_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_out_V_data_V_1_load_B);
    sensitive << ( out_V_data_V_1_sel_wr );
    sensitive << ( out_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_out_V_data_V_1_sel);
    sensitive << ( out_V_data_V_1_sel_rd );

    SC_METHOD(thread_out_V_data_V_1_state_cmp_full);
    sensitive << ( out_V_data_V_1_state );

    SC_METHOD(thread_out_V_data_V_1_vld_in);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln48_reg_208 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_out_V_data_V_1_vld_out);
    sensitive << ( out_V_data_V_1_state );

    SC_METHOD(thread_out_V_last_1_ack_in);
    sensitive << ( out_V_last_1_state );

    SC_METHOD(thread_out_V_last_1_ack_out);
    sensitive << ( out_r_TREADY );

    SC_METHOD(thread_out_V_last_1_data_out);
    sensitive << ( out_V_last_1_payload_A );
    sensitive << ( out_V_last_1_payload_B );
    sensitive << ( out_V_last_1_sel );

    SC_METHOD(thread_out_V_last_1_load_A);
    sensitive << ( out_V_last_1_sel_wr );
    sensitive << ( out_V_last_1_state_cmp_full );

    SC_METHOD(thread_out_V_last_1_load_B);
    sensitive << ( out_V_last_1_sel_wr );
    sensitive << ( out_V_last_1_state_cmp_full );

    SC_METHOD(thread_out_V_last_1_sel);
    sensitive << ( out_V_last_1_sel_rd );

    SC_METHOD(thread_out_V_last_1_state_cmp_full);
    sensitive << ( out_V_last_1_state );

    SC_METHOD(thread_out_V_last_1_vld_in);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln48_reg_208 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_out_V_last_1_vld_out);
    sensitive << ( out_V_last_1_state );

    SC_METHOD(thread_out_r_TDATA);
    sensitive << ( out_V_data_V_1_data_out );

    SC_METHOD(thread_out_r_TDATA_blk_n);
    sensitive << ( out_V_data_V_1_state );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln48_reg_208 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln48_reg_208_pp0_iter1_reg );

    SC_METHOD(thread_out_r_TLAST);
    sensitive << ( out_V_last_1_data_out );

    SC_METHOD(thread_out_r_TVALID);
    sensitive << ( out_V_last_1_state );

    SC_METHOD(thread_stream_tp2_V_V_blk_n);
    sensitive << ( stream_tp2_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln48_reg_208 );

    SC_METHOD(thread_stream_tp2_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln48_reg_208 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_last_fu_172_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( add_ln55_reg_203 );
    sensitive << ( icmp_ln48_fu_161_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln48_fu_157_p1 );

    SC_METHOD(thread_width_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( width_out_empty_n );

    SC_METHOD(thread_width_out_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ch_div_K_empty_n );
    sensitive << ( height_out_empty_n );
    sensitive << ( width_out_empty_n );

    SC_METHOD(thread_zext_ln48_fu_157_p1);
    sensitive << ( i_0_i_i_reg_133 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_r_TREADY );
    sensitive << ( out_V_data_V_1_state );
    sensitive << ( out_V_last_1_state );
    sensitive << ( ch_div_K_empty_n );
    sensitive << ( height_out_empty_n );
    sensitive << ( width_out_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln48_fu_161_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_CS_fsm_state8 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000001";
    out_V_data_V_1_sel_rd = SC_LOGIC_0;
    out_V_data_V_1_sel_wr = SC_LOGIC_0;
    out_V_data_V_1_state = "00";
    out_V_last_1_sel_rd = SC_LOGIC_0;
    out_V_last_1_sel_wr = SC_LOGIC_0;
    out_V_last_1_state = "00";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hs2axis_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_r_TDATA, "(port)out_r_TDATA");
    sc_trace(mVcdFile, out_r_TVALID, "(port)out_r_TVALID");
    sc_trace(mVcdFile, out_r_TREADY, "(port)out_r_TREADY");
    sc_trace(mVcdFile, out_r_TLAST, "(port)out_r_TLAST");
    sc_trace(mVcdFile, ch_div_K_dout, "(port)ch_div_K_dout");
    sc_trace(mVcdFile, ch_div_K_empty_n, "(port)ch_div_K_empty_n");
    sc_trace(mVcdFile, ch_div_K_read, "(port)ch_div_K_read");
    sc_trace(mVcdFile, height_out_dout, "(port)height_out_dout");
    sc_trace(mVcdFile, height_out_empty_n, "(port)height_out_empty_n");
    sc_trace(mVcdFile, height_out_read, "(port)height_out_read");
    sc_trace(mVcdFile, width_out_dout, "(port)width_out_dout");
    sc_trace(mVcdFile, width_out_empty_n, "(port)width_out_empty_n");
    sc_trace(mVcdFile, width_out_read, "(port)width_out_read");
    sc_trace(mVcdFile, stream_tp2_V_V_dout, "(port)stream_tp2_V_V_dout");
    sc_trace(mVcdFile, stream_tp2_V_V_empty_n, "(port)stream_tp2_V_V_empty_n");
    sc_trace(mVcdFile, stream_tp2_V_V_read, "(port)stream_tp2_V_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, out_V_data_V_1_data_out, "out_V_data_V_1_data_out");
    sc_trace(mVcdFile, out_V_data_V_1_vld_in, "out_V_data_V_1_vld_in");
    sc_trace(mVcdFile, out_V_data_V_1_vld_out, "out_V_data_V_1_vld_out");
    sc_trace(mVcdFile, out_V_data_V_1_ack_in, "out_V_data_V_1_ack_in");
    sc_trace(mVcdFile, out_V_data_V_1_ack_out, "out_V_data_V_1_ack_out");
    sc_trace(mVcdFile, out_V_data_V_1_payload_A, "out_V_data_V_1_payload_A");
    sc_trace(mVcdFile, out_V_data_V_1_payload_B, "out_V_data_V_1_payload_B");
    sc_trace(mVcdFile, out_V_data_V_1_sel_rd, "out_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, out_V_data_V_1_sel_wr, "out_V_data_V_1_sel_wr");
    sc_trace(mVcdFile, out_V_data_V_1_sel, "out_V_data_V_1_sel");
    sc_trace(mVcdFile, out_V_data_V_1_load_A, "out_V_data_V_1_load_A");
    sc_trace(mVcdFile, out_V_data_V_1_load_B, "out_V_data_V_1_load_B");
    sc_trace(mVcdFile, out_V_data_V_1_state, "out_V_data_V_1_state");
    sc_trace(mVcdFile, out_V_data_V_1_state_cmp_full, "out_V_data_V_1_state_cmp_full");
    sc_trace(mVcdFile, out_V_last_1_data_out, "out_V_last_1_data_out");
    sc_trace(mVcdFile, out_V_last_1_vld_in, "out_V_last_1_vld_in");
    sc_trace(mVcdFile, out_V_last_1_vld_out, "out_V_last_1_vld_out");
    sc_trace(mVcdFile, out_V_last_1_ack_in, "out_V_last_1_ack_in");
    sc_trace(mVcdFile, out_V_last_1_ack_out, "out_V_last_1_ack_out");
    sc_trace(mVcdFile, out_V_last_1_payload_A, "out_V_last_1_payload_A");
    sc_trace(mVcdFile, out_V_last_1_payload_B, "out_V_last_1_payload_B");
    sc_trace(mVcdFile, out_V_last_1_sel_rd, "out_V_last_1_sel_rd");
    sc_trace(mVcdFile, out_V_last_1_sel_wr, "out_V_last_1_sel_wr");
    sc_trace(mVcdFile, out_V_last_1_sel, "out_V_last_1_sel");
    sc_trace(mVcdFile, out_V_last_1_load_A, "out_V_last_1_load_A");
    sc_trace(mVcdFile, out_V_last_1_load_B, "out_V_last_1_load_B");
    sc_trace(mVcdFile, out_V_last_1_state, "out_V_last_1_state");
    sc_trace(mVcdFile, out_V_last_1_state_cmp_full, "out_V_last_1_state_cmp_full");
    sc_trace(mVcdFile, out_r_TDATA_blk_n, "out_r_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln48_reg_208, "icmp_ln48_reg_208");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, icmp_ln48_reg_208_pp0_iter1_reg, "icmp_ln48_reg_208_pp0_iter1_reg");
    sc_trace(mVcdFile, ch_div_K_blk_n, "ch_div_K_blk_n");
    sc_trace(mVcdFile, height_out_blk_n, "height_out_blk_n");
    sc_trace(mVcdFile, width_out_blk_n, "width_out_blk_n");
    sc_trace(mVcdFile, stream_tp2_V_V_blk_n, "stream_tp2_V_V_blk_n");
    sc_trace(mVcdFile, i_0_i_i_reg_133, "i_0_i_i_reg_133");
    sc_trace(mVcdFile, ch_div_K_read_reg_177, "ch_div_K_read_reg_177");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, height_out_read_reg_182, "height_out_read_reg_182");
    sc_trace(mVcdFile, width_out_read_reg_187, "width_out_read_reg_187");
    sc_trace(mVcdFile, mul_ln48_fu_144_p2, "mul_ln48_fu_144_p2");
    sc_trace(mVcdFile, mul_ln48_reg_192, "mul_ln48_reg_192");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, mul_ln48_1_fu_148_p2, "mul_ln48_1_fu_148_p2");
    sc_trace(mVcdFile, mul_ln48_1_reg_197, "mul_ln48_1_reg_197");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln55_fu_152_p2, "add_ln55_fu_152_p2");
    sc_trace(mVcdFile, add_ln55_reg_203, "add_ln55_reg_203");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln48_fu_161_p2, "icmp_ln48_fu_161_p2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter0, "ap_block_state5_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state6_io, "ap_block_state6_io");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter2, "ap_block_state7_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state7_io, "ap_block_state7_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_166_p2, "i_fu_166_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_last_fu_172_p2, "tmp_last_fu_172_p2");
    sc_trace(mVcdFile, tmp_last_reg_217, "tmp_last_reg_217");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state5, "ap_condition_pp0_exit_iter0_state5");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, zext_ln48_fu_157_p1, "zext_ln48_fu_157_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_block_state8, "ap_block_state8");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

hs2axis::~hs2axis() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void hs2axis::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                    !(esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_1) || esl_seteq<1,2,2>(ap_const_lv2_1, out_V_last_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_3)) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_1_state.read()))))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state5.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state5.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state5.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_fu_161_p2.read()))) {
        i_0_i_i_reg_133 = i_fu_166_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_0_i_i_reg_133 = ap_const_lv31_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        out_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_out.read()))) {
            out_V_data_V_1_sel_rd =  (sc_logic) (~out_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        out_V_data_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_in.read()))) {
            out_V_data_V_1_sel_wr =  (sc_logic) (~out_V_data_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        out_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_2)))) {
            out_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
                     esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
                     esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_1)))) {
            out_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_ack_out.read()))))) {
            out_V_data_V_1_state = ap_const_lv2_3;
        } else {
            out_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        out_V_last_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_vld_out.read()))) {
            out_V_last_1_sel_rd =  (sc_logic) (~out_V_last_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        out_V_last_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_ack_in.read()))) {
            out_V_last_1_sel_wr =  (sc_logic) (~out_V_last_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        out_V_last_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, out_V_last_1_state.read())))) {
            out_V_last_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_V_last_1_state.read())))) {
            out_V_last_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, out_V_last_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, out_V_last_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, out_V_last_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_ack_out.read()))))) {
            out_V_last_1_state = ap_const_lv2_3;
        } else {
            out_V_last_1_state = ap_const_lv2_2;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        add_ln55_reg_203 = add_ln55_fu_152_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, ch_div_K_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, height_out_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_out_empty_n.read())))) {
        ch_div_K_read_reg_177 = ch_div_K_dout.read();
        height_out_read_reg_182 = height_out_dout.read();
        width_out_read_reg_187 = width_out_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln48_reg_208 = icmp_ln48_fu_161_p2.read();
        icmp_ln48_reg_208_pp0_iter1_reg = icmp_ln48_reg_208.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mul_ln48_1_reg_197 = mul_ln48_1_fu_148_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mul_ln48_reg_192 = mul_ln48_fu_144_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_load_A.read())) {
        out_V_data_V_1_payload_A = stream_tp2_V_V_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_load_B.read())) {
        out_V_data_V_1_payload_B = stream_tp2_V_V_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_load_A.read())) {
        out_V_last_1_payload_A =  (sc_logic) (tmp_last_reg_217.read()[0]);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_load_B.read())) {
        out_V_last_1_payload_B =  (sc_logic) (tmp_last_reg_217.read()[0]);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_fu_161_p2.read()))) {
        tmp_last_reg_217 = tmp_last_fu_172_p2.read();
    }
}

void hs2axis::thread_add_ln55_fu_152_p2() {
    add_ln55_fu_152_p2 = (!mul_ln48_1_reg_197.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln48_1_reg_197.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void hs2axis::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[4];
}

void hs2axis::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void hs2axis::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void hs2axis::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void hs2axis::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void hs2axis::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[5];
}

void hs2axis::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void hs2axis::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read()) && esl_seteq<1,1,1>(ap_const_logic_0, stream_tp2_V_V_empty_n.read()));
}

void hs2axis::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, stream_tp2_V_V_empty_n.read())) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state6_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state7_io.read())));
}

void hs2axis::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, stream_tp2_V_V_empty_n.read())) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state6_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state7_io.read())));
}

void hs2axis::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, ch_div_K_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, height_out_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_out_empty_n.read()));
}

void hs2axis::thread_ap_block_state5_pp0_stage0_iter0() {
    ap_block_state5_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void hs2axis::thread_ap_block_state6_io() {
    ap_block_state6_io = (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_ack_in.read()));
}

void hs2axis::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read()) && esl_seteq<1,1,1>(ap_const_logic_0, stream_tp2_V_V_empty_n.read()));
}

void hs2axis::thread_ap_block_state7_io() {
    ap_block_state7_io = (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_data_V_1_ack_in.read()));
}

void hs2axis::thread_ap_block_state7_pp0_stage0_iter2() {
    ap_block_state7_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void hs2axis::thread_ap_block_state8() {
    ap_block_state8 = (esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_1) || esl_seteq<1,2,2>(ap_const_lv2_1, out_V_last_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_3)) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_1_state.read())));
}

void hs2axis::thread_ap_condition_pp0_exit_iter0_state5() {
    if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln48_fu_161_p2.read())) {
        ap_condition_pp0_exit_iter0_state5 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state5 = ap_const_logic_0;
    }
}

void hs2axis::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         !(esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_1) || esl_seteq<1,2,2>(ap_const_lv2_1, out_V_last_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_3)) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_1_state.read()))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void hs2axis::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void hs2axis::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void hs2axis::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void hs2axis::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         !(esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_1) || esl_seteq<1,2,2>(ap_const_lv2_1, out_V_last_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_3)) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_1_state.read()))))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void hs2axis::thread_ch_div_K_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ch_div_K_blk_n = ch_div_K_empty_n.read();
    } else {
        ch_div_K_blk_n = ap_const_logic_1;
    }
}

void hs2axis::thread_ch_div_K_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, ch_div_K_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, height_out_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_out_empty_n.read())))) {
        ch_div_K_read = ap_const_logic_1;
    } else {
        ch_div_K_read = ap_const_logic_0;
    }
}

void hs2axis::thread_height_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        height_out_blk_n = height_out_empty_n.read();
    } else {
        height_out_blk_n = ap_const_logic_1;
    }
}

void hs2axis::thread_height_out_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, ch_div_K_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, height_out_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_out_empty_n.read())))) {
        height_out_read = ap_const_logic_1;
    } else {
        height_out_read = ap_const_logic_0;
    }
}

void hs2axis::thread_i_fu_166_p2() {
    i_fu_166_p2 = (!i_0_i_i_reg_133.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(i_0_i_i_reg_133.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void hs2axis::thread_icmp_ln48_fu_161_p2() {
    icmp_ln48_fu_161_p2 = (!zext_ln48_fu_157_p1.read().is_01() || !mul_ln48_1_reg_197.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln48_fu_157_p1.read()) < sc_bigint<32>(mul_ln48_1_reg_197.read()));
}

void hs2axis::thread_mul_ln48_1_fu_148_p2() {
    mul_ln48_1_fu_148_p2 = (!mul_ln48_reg_192.read().is_01() || !height_out_read_reg_182.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln48_reg_192.read()) * sc_bigint<32>(height_out_read_reg_182.read());
}

void hs2axis::thread_mul_ln48_fu_144_p2() {
    mul_ln48_fu_144_p2 = (!ch_div_K_read_reg_177.read().is_01() || !width_out_read_reg_187.read().is_01())? sc_lv<32>(): sc_bigint<32>(ch_div_K_read_reg_177.read()) * sc_bigint<32>(width_out_read_reg_187.read());
}

void hs2axis::thread_out_V_data_V_1_ack_in() {
    out_V_data_V_1_ack_in = out_V_data_V_1_state.read()[1];
}

void hs2axis::thread_out_V_data_V_1_ack_out() {
    out_V_data_V_1_ack_out = out_r_TREADY.read();
}

void hs2axis::thread_out_V_data_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_data_V_1_sel.read())) {
        out_V_data_V_1_data_out = out_V_data_V_1_payload_B.read();
    } else {
        out_V_data_V_1_data_out = out_V_data_V_1_payload_A.read();
    }
}

void hs2axis::thread_out_V_data_V_1_load_A() {
    out_V_data_V_1_load_A = (out_V_data_V_1_state_cmp_full.read() & ~out_V_data_V_1_sel_wr.read());
}

void hs2axis::thread_out_V_data_V_1_load_B() {
    out_V_data_V_1_load_B = (out_V_data_V_1_sel_wr.read() & out_V_data_V_1_state_cmp_full.read());
}

void hs2axis::thread_out_V_data_V_1_sel() {
    out_V_data_V_1_sel = out_V_data_V_1_sel_rd.read();
}

void hs2axis::thread_out_V_data_V_1_state_cmp_full() {
    out_V_data_V_1_state_cmp_full =  (sc_logic) ((!out_V_data_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(out_V_data_V_1_state.read() != ap_const_lv2_1))[0];
}

void hs2axis::thread_out_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        out_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void hs2axis::thread_out_V_data_V_1_vld_out() {
    out_V_data_V_1_vld_out = out_V_data_V_1_state.read()[0];
}

void hs2axis::thread_out_V_last_1_ack_in() {
    out_V_last_1_ack_in = out_V_last_1_state.read()[1];
}

void hs2axis::thread_out_V_last_1_ack_out() {
    out_V_last_1_ack_out = out_r_TREADY.read();
}

void hs2axis::thread_out_V_last_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, out_V_last_1_sel.read())) {
        out_V_last_1_data_out = out_V_last_1_payload_B.read();
    } else {
        out_V_last_1_data_out = out_V_last_1_payload_A.read();
    }
}

void hs2axis::thread_out_V_last_1_load_A() {
    out_V_last_1_load_A = (out_V_last_1_state_cmp_full.read() & ~out_V_last_1_sel_wr.read());
}

void hs2axis::thread_out_V_last_1_load_B() {
    out_V_last_1_load_B = (out_V_last_1_sel_wr.read() & out_V_last_1_state_cmp_full.read());
}

void hs2axis::thread_out_V_last_1_sel() {
    out_V_last_1_sel = out_V_last_1_sel_rd.read();
}

void hs2axis::thread_out_V_last_1_state_cmp_full() {
    out_V_last_1_state_cmp_full =  (sc_logic) ((!out_V_last_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(out_V_last_1_state.read() != ap_const_lv2_1))[0];
}

void hs2axis::thread_out_V_last_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_V_last_1_vld_in = ap_const_logic_1;
    } else {
        out_V_last_1_vld_in = ap_const_logic_0;
    }
}

void hs2axis::thread_out_V_last_1_vld_out() {
    out_V_last_1_vld_out = out_V_last_1_state.read()[0];
}

void hs2axis::thread_out_r_TDATA() {
    out_r_TDATA = out_V_data_V_1_data_out.read();
}

void hs2axis::thread_out_r_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208_pp0_iter1_reg.read())))) {
        out_r_TDATA_blk_n = out_V_data_V_1_state.read()[1];
    } else {
        out_r_TDATA_blk_n = ap_const_logic_1;
    }
}

void hs2axis::thread_out_r_TLAST() {
    out_r_TLAST = out_V_last_1_data_out.read();
}

void hs2axis::thread_out_r_TVALID() {
    out_r_TVALID = out_V_last_1_state.read()[0];
}

void hs2axis::thread_stream_tp2_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read()))) {
        stream_tp2_V_V_blk_n = stream_tp2_V_V_empty_n.read();
    } else {
        stream_tp2_V_V_blk_n = ap_const_logic_1;
    }
}

void hs2axis::thread_stream_tp2_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln48_reg_208.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        stream_tp2_V_V_read = ap_const_logic_1;
    } else {
        stream_tp2_V_V_read = ap_const_logic_0;
    }
}

void hs2axis::thread_tmp_last_fu_172_p2() {
    tmp_last_fu_172_p2 = (!zext_ln48_fu_157_p1.read().is_01() || !add_ln55_reg_203.read().is_01())? sc_lv<1>(): sc_lv<1>(zext_ln48_fu_157_p1.read() == add_ln55_reg_203.read());
}

void hs2axis::thread_width_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        width_out_blk_n = width_out_empty_n.read();
    } else {
        width_out_blk_n = ap_const_logic_1;
    }
}

void hs2axis::thread_width_out_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, ch_div_K_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, height_out_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_out_empty_n.read())))) {
        width_out_read = ap_const_logic_1;
    } else {
        width_out_read = ap_const_logic_0;
    }
}

void hs2axis::thread_zext_ln48_fu_157_p1() {
    zext_ln48_fu_157_p1 = esl_zext<32,31>(i_0_i_i_reg_133.read());
}

void hs2axis::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, ch_div_K_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, height_out_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, width_out_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 16 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln48_fu_161_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln48_fu_161_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && !(esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_1) || esl_seteq<1,2,2>(ap_const_lv2_1, out_V_last_1_state.read()) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(out_V_data_V_1_state.read(), ap_const_lv2_3)) || (esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY.read()) && 
  esl_seteq<1,2,2>(ap_const_lv2_3, out_V_last_1_state.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

}

